name: Setup Node and install dependencies
description: Configure Node.js with npm cache and install dependencies.
inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: "20"
runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      shell: bash
      run: npm ci --prefer-offline --no-audit
